@startuml

actor Klient
note left DystrybutorPaliwa: Scenariusz korzystania z Dystrybutora Paliwa

activate DystrybutorPaliwa
DystrybutorPaliwa -> Platnosc : tankuj()

    activate Platnosc
        Platnosc -> Rachunek : zaplac()
    
        activate Rachunek
        Rachunek -> Rachunek : wyborRachunku()
    
        return zaplac()
    
    return tankuj()

deactivate DystrybutorPaliwa
deactivate Rachunek
deactivate Platnosc

note left DystrybutorPaliwa: Scenariusz korzystania z Myjni
activate Myjnia
Myjnia -> Platnosc : umyj()

    activate Platnosc
        Platnosc -> Rachunek : zaplac()
    
        activate Rachunek
        Rachunek -> Rachunek : wyborRachunku()
    
        return zaplac()
    
    return umyj()

deactivate Myjnia
deactivate Rachunek
deactivate Platnosc

note left DystrybutorPaliwa: Scenariusz korzystania z Odkurzacza
activate Odkurzacz
Odkurzacz -> Platnosc : odkurz()

    activate Platnosc
        Platnosc -> Rachunek : zaplac()
    
        activate Rachunek
        Rachunek -> Rachunek : wyborRachunku()
    
        return zaplac()
    
    return odkurz()

deactivate Odkurzacz
deactivate Rachunek
deactivate Platnosc

@enduml